version: '3'

services:
  api:
    build: api/.
    image: mustachebash:local
    tty: true
    volumes:
      - ./api:/mustachebash
      - ./logs:/mustachebash/logs
    command: sh -c "cd /mustachebash && npm run debug"
    environment:
      - NODE_ENV=development
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - JWT_SECRET
      - JWT_TRANSACTION_SECRET
      - JWT_TICKET_SECRET
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
      - MAILCHIMP_DOMAIN
      - MAILCHIMP_API_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    ports:
      - "9229:9229"

  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - "4000:80"
      - "5000:8080"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./rootCA.pem:/etc/nginx/certs/rootCA.pem
      - ./server.key:/etc/nginx/certs/server.key
      - ./server.crt:/etc/nginx/certs/server.crt
  rethinkdb:
    image: rethinkdb:2.3.6
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - ./data:/data
