version: '3.7'

volumes:
    node_modules:

services:
  installer:
    image: node:18.10-alpine
    working_dir: /mustachebash
    command: npm i
    environment:
        NODE_ENV: development
    volumes:
        - type: bind
          source: ./api
          target: /mustachebash
        - type: volume
          source: node_modules
          target: /mustachebash/node_modules
  api:
    depends_on:
      - installer
      - nginx
      - rethinkdb
    image: node:18.10-alpine
    working_dir: /mustachebash
    tty: true
    volumes:
      - type: bind
        source: ./api
        target: /mustachebash
      - type: bind
        read_only: true
        source: ./await.sh
        target: /etc/await.sh
      - type: volume
        source: node_modules
        target: /mustachebash/node_modules
    command: sh -c "/etc/await.sh node_modules/.bin/nodemon npm run debug"
    environment:
      - NODE_ENV=development
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - JWT_SECRET
      - JWT_TRANSACTION_SECRET
      - JWT_TICKET_SECRET
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
      - MAILCHIMP_DOMAIN
      - MAILCHIMP_API_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    ports:
      - "9229:9229"

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "5000:8080"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./rootCA.pem:/etc/nginx/certs/rootCA.pem
      - ./server.key:/etc/nginx/certs/server.key
      - ./server.crt:/etc/nginx/certs/server.crt
  rethinkdb:
    image: rethinkdb:2.4.2
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - ./data:/data
