version: '3'

services:
  api:
    build: api/.
    image: mustachebash:local
    tty: true
    volumes:
      - ./api:/mustachebash
      - ./logs:/mustachebash/logs
    command: sh -c "cd /mustachebash && npm run debug"
    environment:
      - NODE_ENV=development
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - JWT_SECRET=fr344moiioa94kla3rnjl8cnjlsa
      - JWT_TRANSACTION_SECRET=8f14902ffe5f09996178e9630c58915c99aedf9a6c354a8a
      - JWT_TICKET_SECRET=5e3ed05df78e69fe6acc2004fffa759e915b6ad9b379e506
      - DONATION_ID=11c2f51e-407d-45be-b8a0-8247ac2f9cd3
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
      - MAILCHIMP_DOMAIN
      - MAILCHIMP_API_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    ports:
      - "9229:9229"

  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - "4000:80"
      - "5000:8080"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./mustachebash.com/dist:/dist
      - ./admin/dist:/admin-dist

  rethinkdb:
    image: rethinkdb:2.3.6
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - ./data:/data
